/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActiveModel {
    /// The Name of a model available by workers in this horde.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// How many of workers in this horde are running this model.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The average speed of generation for this model
    #[serde(rename = "performance", skip_serializing_if = "Option::is_none")]
    pub performance: Option<f32>,
}

impl ActiveModel {
    pub fn new() -> ActiveModel {
        ActiveModel {
            name: None,
            count: None,
            performance: None,
        }
    }
}


