/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeletedWorker {
    /// The ID of the deleted worker
    #[serde(rename = "deleted_id", skip_serializing_if = "Option::is_none")]
    pub deleted_id: Option<String>,
    /// The Name of the deleted worker
    #[serde(rename = "deleted_name", skip_serializing_if = "Option::is_none")]
    pub deleted_name: Option<String>,
}

impl DeletedWorker {
    pub fn new() -> DeletedWorker {
        DeletedWorker {
            deleted_id: None,
            deleted_name: None,
        }
    }
}


