/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GenerationSubmitted {
    /// The amount of kudos gained for submitting this request
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<f32>,
}

impl GenerationSubmitted {
    pub fn new() -> GenerationSubmitted {
        GenerationSubmitted {
            reward: None,
        }
    }
}


