/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Generation {
    /// The UUID of the worker which generated this image
    #[serde(rename = "worker_id", skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
    /// The name of the worker which generated this image
    #[serde(rename = "worker_name", skip_serializing_if = "Option::is_none")]
    pub worker_name: Option<String>,
    /// The model which generated this image
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

impl Generation {
    pub fn new() -> Generation {
        Generation {
            worker_id: None,
            worker_name: None,
            model: None,
        }
    }
}


