/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GenerationStable {
    /// The UUID of the worker which generated this image
    #[serde(rename = "worker_id", skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
    /// The name of the worker which generated this image
    #[serde(rename = "worker_name", skip_serializing_if = "Option::is_none")]
    pub worker_name: Option<String>,
    /// The model which generated this image
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// The generated image as a Base64-encoded .webp file
    #[serde(rename = "img", skip_serializing_if = "Option::is_none")]
    pub img: Option<String>,
    /// The seed which generated this image
    #[serde(rename = "seed", skip_serializing_if = "Option::is_none")]
    pub seed: Option<String>,
}

impl GenerationStable {
    pub fn new() -> GenerationStable {
        GenerationStable {
            worker_id: None,
            worker_name: None,
            model: None,
            img: None,
            seed: None,
        }
    }
}


