/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HordeModes {
    /// When True, this Horde will not accept new requests for image generation, but will finish processing the ones currently in the queue.
    #[serde(rename = "maintenance_mode", skip_serializing_if = "Option::is_none")]
    pub maintenance_mode: Option<bool>,
    /// When True, this Horde will not only accept worker explicitly invited to join.
    #[serde(rename = "invite_only_mode", skip_serializing_if = "Option::is_none")]
    pub invite_only_mode: Option<bool>,
    /// When True, this Horde will not always provide full information in order to throw off attackers.
    #[serde(rename = "raid_mode", skip_serializing_if = "Option::is_none")]
    pub raid_mode: Option<bool>,
}

impl HordeModes {
    pub fn new() -> HordeModes {
        HordeModes {
            maintenance_mode: None,
            invite_only_mode: None,
            raid_mode: None,
        }
    }
}


