/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KudosTransferred {
    /// The amount of Kudos tranferred
    #[serde(rename = "transferred", skip_serializing_if = "Option::is_none")]
    pub transferred: Option<i32>,
}

impl KudosTransferred {
    pub fn new() -> KudosTransferred {
        KudosTransferred {
            transferred: None,
        }
    }
}


