/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModelPayloadStableAllOf {
    /// The prompt which will be sent to Stable Diffusion to generate an image
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(rename = "ddim_steps", skip_serializing_if = "Option::is_none")]
    pub ddim_steps: Option<i32>,
    /// The amount of images to generate
    #[serde(rename = "n_iter", skip_serializing_if = "Option::is_none")]
    pub n_iter: Option<i32>,
    /// When true will apply NSFW censoring model on the generation
    #[serde(rename = "use_nsfw_censor", skip_serializing_if = "Option::is_none")]
    pub use_nsfw_censor: Option<bool>,
}

impl ModelPayloadStableAllOf {
    pub fn new() -> ModelPayloadStableAllOf {
        ModelPayloadStableAllOf {
            prompt: None,
            ddim_steps: None,
            n_iter: None,
            use_nsfw_censor: None,
        }
    }
}


