/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModelGenerationInputStableAllOf {
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<i32>,
    /// The amount of images to generate
    #[serde(rename = "n", skip_serializing_if = "Option::is_none")]
    pub n: Option<i32>,
}

impl ModelGenerationInputStableAllOf {
    pub fn new() -> ModelGenerationInputStableAllOf {
        ModelGenerationInputStableAllOf {
            steps: None,
            n: None,
        }
    }
}


