/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModifyWorker {
    /// The new state of the 'maintenance' var for this worker. When True, this worker will not pick up any new requests.
    #[serde(rename = "maintenance", skip_serializing_if = "Option::is_none")]
    pub maintenance: Option<bool>,
    /// The new state of the 'paused' var for this worker. When True, this worker will not be given any new requests.
    #[serde(rename = "paused", skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
    /// The new state of the 'info' var for this worker.
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,
    /// The new name for this this worker.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ModifyWorker {
    pub fn new() -> ModifyWorker {
        ModifyWorker {
            maintenance: None,
            paused: None,
            info: None,
            name: None,
        }
    }
}


