/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Newspiece {
    /// The date this newspiece was published
    #[serde(rename = "date_published", skip_serializing_if = "Option::is_none")]
    pub date_published: Option<String>,
    /// The actual piece of news
    #[serde(rename = "newspiece", skip_serializing_if = "Option::is_none")]
    pub newspiece: Option<String>,
    /// How critical this piece of news is.
    #[serde(rename = "importance", skip_serializing_if = "Option::is_none")]
    pub importance: Option<String>,
}

impl Newspiece {
    pub fn new() -> Newspiece {
        Newspiece {
            date_published: None,
            newspiece: None,
            importance: None,
        }
    }
}


