/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NoValidRequestFoundStableAllOf {
    /// How many waiting requests were skipped because they demanded a higher size than this worker provides
    #[serde(rename = "max_pixels", skip_serializing_if = "Option::is_none")]
    pub max_pixels: Option<i32>,
}

impl NoValidRequestFoundStableAllOf {
    pub fn new() -> NoValidRequestFoundStableAllOf {
        NoValidRequestFoundStableAllOf {
            max_pixels: None,
        }
    }
}


