/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PopInputStableAllOf {
    /// The maximum amount of pixels this worker can generate
    #[serde(rename = "max_pixels", skip_serializing_if = "Option::is_none")]
    pub max_pixels: Option<i32>,
}

impl PopInputStableAllOf {
    pub fn new() -> PopInputStableAllOf {
        PopInputStableAllOf {
            max_pixels: None,
        }
    }
}


