/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PopInput {
    /// The Name of the Worker
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "priority_usernames", skip_serializing_if = "Option::is_none")]
    pub priority_usernames: Option<Vec<String>>,
    /// Whether this worker can generate NSFW requests or not.
    #[serde(rename = "nsfw", skip_serializing_if = "Option::is_none")]
    pub nsfw: Option<bool>,
    #[serde(rename = "blacklist", skip_serializing_if = "Option::is_none")]
    pub blacklist: Option<Vec<String>>,
    #[serde(rename = "models", skip_serializing_if = "Option::is_none")]
    pub models: Option<Vec<String>>,
    /// The version of the bridge used by this worker
    #[serde(rename = "bridge_version", skip_serializing_if = "Option::is_none")]
    pub bridge_version: Option<i32>,
}

impl PopInput {
    pub fn new() -> PopInput {
        PopInput {
            name: None,
            priority_usernames: None,
            nsfw: None,
            blacklist: None,
            models: None,
            bridge_version: None,
        }
    }
}


