/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostJobSubmitRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "generation", skip_serializing_if = "Option::is_none")]
    pub generation: Option<String>,
    #[serde(rename = "seed", skip_serializing_if = "Option::is_none")]
    pub seed: Option<String>,
}

impl PostJobSubmitRequest {
    pub fn new() -> PostJobSubmitRequest {
        PostJobSubmitRequest {
            id: None,
            generation: None,
            seed: None,
        }
    }
}


