/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutHordeModesRequest {
    #[serde(rename = "maintenance", skip_serializing_if = "Option::is_none")]
    pub maintenance: Option<bool>,
    #[serde(rename = "invite_only", skip_serializing_if = "Option::is_none")]
    pub invite_only: Option<bool>,
    #[serde(rename = "raid", skip_serializing_if = "Option::is_none")]
    pub raid: Option<bool>,
}

impl PutHordeModesRequest {
    pub fn new() -> PutHordeModesRequest {
        PutHordeModesRequest {
            maintenance: None,
            invite_only: None,
            raid: None,
        }
    }
}


