/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestStatusStable {
    /// The amount of finished images in this request
    #[serde(rename = "finished", skip_serializing_if = "Option::is_none")]
    pub finished: Option<i32>,
    /// The amount of still processing images in this request
    #[serde(rename = "processing", skip_serializing_if = "Option::is_none")]
    pub processing: Option<i32>,
    /// The amount of images waiting to be picked up by a worker
    #[serde(rename = "waiting", skip_serializing_if = "Option::is_none")]
    pub waiting: Option<i32>,
    /// True when all images in this request are done. Else False.
    #[serde(rename = "done", skip_serializing_if = "Option::is_none")]
    pub done: Option<bool>,
    /// True when this request caused an internal server error and cannot be completed.
    #[serde(rename = "faulted", skip_serializing_if = "Option::is_none")]
    pub faulted: Option<bool>,
    /// The expected amount to wait (in seconds) to generate all images in this request
    #[serde(rename = "wait_time", skip_serializing_if = "Option::is_none")]
    pub wait_time: Option<i32>,
    /// The position in the requests queue. This position is determined by relative Kudos amounts.
    #[serde(rename = "queue_position", skip_serializing_if = "Option::is_none")]
    pub queue_position: Option<i32>,
    #[serde(rename = "generations", skip_serializing_if = "Option::is_none")]
    pub generations: Option<Vec<crate::models::GenerationStable>>,
}

impl RequestStatusStable {
    pub fn new() -> RequestStatusStable {
        RequestStatusStable {
            finished: None,
            processing: None,
            waiting: None,
            done: None,
            faulted: None,
            wait_time: None,
            queue_position: None,
            generations: None,
        }
    }
}


