/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsageDetailsStableAllOf {
    /// How many megapixelsteps this user has requested
    #[serde(rename = "megapixelsteps", skip_serializing_if = "Option::is_none")]
    pub megapixelsteps: Option<f32>,
}

impl UsageDetailsStableAllOf {
    pub fn new() -> UsageDetailsStableAllOf {
        UsageDetailsStableAllOf {
            megapixelsteps: None,
        }
    }
}


