/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserKudosDetails {
    /// The ammount of Kudos accumulated or used for generating images.
    #[serde(rename = "accumulated", skip_serializing_if = "Option::is_none")]
    pub accumulated: Option<f32>,
    /// The amount of Kudos this user has given to other users.
    #[serde(rename = "gifted", skip_serializing_if = "Option::is_none")]
    pub gifted: Option<f32>,
    /// The amount of Kudos this user has been given by the Horde admins.
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<f32>,
    /// The amount of Kudos this user has been given by other users.
    #[serde(rename = "received", skip_serializing_if = "Option::is_none")]
    pub received: Option<f32>,
    /// The amount of Kudos this user has received from recurring rewards.
    #[serde(rename = "recurring", skip_serializing_if = "Option::is_none")]
    pub recurring: Option<f32>,
}

impl UserKudosDetails {
    pub fn new() -> UserKudosDetails {
        UserKudosDetails {
            accumulated: None,
            gifted: None,
            admin: None,
            received: None,
            recurring: None,
        }
    }
}


