/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserDetailsStableAllOf {
    #[serde(rename = "kudos_details", skip_serializing_if = "Option::is_none")]
    pub kudos_details: Option<Box<crate::models::UserKudosDetails>>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<crate::models::UsageDetailsStable>>,
    #[serde(rename = "contributions", skip_serializing_if = "Option::is_none")]
    pub contributions: Option<Box<crate::models::ContributionsDetailsStable>>,
}

impl UserDetailsStableAllOf {
    pub fn new() -> UserDetailsStableAllOf {
        UserDetailsStableAllOf {
            kudos_details: None,
            usage: None,
            contributions: None,
        }
    }
}


