/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkerKudosDetails {
    /// How much Kudos this worker has received for generating images
    #[serde(rename = "generated", skip_serializing_if = "Option::is_none")]
    pub generated: Option<f32>,
    /// How much Kudos this worker has received for staying online longer
    #[serde(rename = "uptime", skip_serializing_if = "Option::is_none")]
    pub uptime: Option<i32>,
}

impl WorkerKudosDetails {
    pub fn new() -> WorkerKudosDetails {
        WorkerKudosDetails {
            generated: None,
            uptime: None,
        }
    }
}


