/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkerDetailsStableAllOf {
    /// The maximum pixels in resolution this workr can generate
    #[serde(rename = "max_pixels", skip_serializing_if = "Option::is_none")]
    pub max_pixels: Option<i32>,
    /// How many megapixelsteps this worker has generated until now
    #[serde(rename = "megapixelsteps_generated", skip_serializing_if = "Option::is_none")]
    pub megapixelsteps_generated: Option<f32>,
}

impl WorkerDetailsStableAllOf {
    pub fn new() -> WorkerDetailsStableAllOf {
        WorkerDetailsStableAllOf {
            max_pixels: None,
            megapixelsteps_generated: None,
        }
    }
}


